name: fslint-unofficial
version: git
summary: File System Lint detector and cleaner
description: |
  FSlint - A utility to find File System lint.
  This includes duplicate files, empty directories,
  problematic filenames, etc.
license: GPL-3.0
base: core18
grade: stable
confinement: strict
architectures:
  - build-on: amd64
  - build-on: 'i386'

icon: fslint_icon.png

compression: lzo

apps:
  fslint-unofficial:
    command: desktop-launch $SNAP/usr/bin/fslint-gui
    desktop: usr/share/applications/fslint.desktop
    environment:
      # Fallback to XWayland if running in a Wayland session as GTK2 don't support it
      DISABLE_WAYLAND: 1
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - removable-media
      - unity7
      - wayland
      - x11

layout:
  /usr/share/applications/fslint.desktop:
    bind-file: $SNAP/usr/share/applications/fslint.desktop
  /usr/share/doc/fslint:
    bind: $SNAP/usr/share/doc/fslint
  /usr/share/fslint:
    bind: $SNAP/usr/share/fslint
  /usr/share/locale:
    bind: $SNAP/usr/share/locale

parts:
  fslint:
    plugin: nil
    stage-packages:
      - fslint
    after:
      - desktop-gtk2
  desktop-gtk2:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk2"]
    build-packages:
      - build-essential
      - libgtk2.0-dev
    stage-packages:
      - adwaita-icon-theme
      - dmz-cursor-theme
      - fontconfig
      - gnome-themes-standard
      - ibus-gtk
      - libappindicator1
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-0
      - libgtk2.0-bin
      - libibus-1.0-5
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - light-themes
      - locales-all
      - shared-mime-info
      - ttf-ubuntu-font-family
      - unity-gtk2-module
      - xdg-user-dirs

plugs:
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk2-common-themes
  gtk-2-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes:sounds-themes
