name: fslint
version: git
summary: FSlint
description: |
  File System Lint detector and cleaner.
base: core18
confinement: devmode

parts:
  pkg:
    plugin: nil
    stage-packages:
      - python-gtk2
      - python-glade2
      - fslint

apps:
  fslint-gui:
    command: fslint-gui
